keys:
  - &nmurray_nitro BE06888200FCFE24713489557530F40B1361F796
  - &titan age18ewkj2vf2uskukrusq5hnghrndeflalfes64dq3g273kyx29nprqvwz9n4
  - &mqtt age1lmykymddt6kyfkggxj3xha8y83u4dq02egxkdud6w4slep8f7udsz9je63
  - &influxdb age12ghzmxgcrpf5vwxz8xzz5tnmneruwfjclk33lnkcja4tf6yry5as72v4s2
  - &immich age1rxsevsvkdz6lngau2p5jdh2fjhrdgdlmzpcvwyvua8erc2zcm3usca7svr
  - &mygarage age1gwx224g4enkrpfx89zxxk0qr826yapsl8pz20zwc2uvdfwhv9glqpg54vs
  - &nextcloud age1rs2ucyrrfayzprmq5ezmlaavq27jkkqjk099hywstnjyrr0734vq4n3fxu
  - &caddy age1f3xesh6ps709gdddnaaw9a79264wkewa3t0p4w02r64x5yww6dfqeupfsp
  - &frigate age1rgx38hrym2zr53wxgs0wvensa0evwamjawalmgvxkl9w26ln7ddq8qr2t0

creation_rules:
  - path_regex: secrets/titan/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan

  - path_regex: secrets/influxdb/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan
          - *influxdb

  - path_regex: secrets/mqtt/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan
          - *mqtt

  - path_regex: secrets/immich/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan
          - *immich

  - path_regex: secrets/mygarage/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan
          - *mygarage   # add after container's age key is known
  - path_regex: secrets/nextcloud/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan
          - *nextcloud   # add after container's age key is knowna

  - path_regex: secrets/caddy/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan
          - *caddy

  - path_regex: secrets/frigate/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
          - *nmurray_nitro
        age:
          - *titan
          - *frigate

