influxdb-token-env: ENC[AES256_GCM,data:vTs1VgXub3u+I0aS4d5uUSeItY9G8l1rBG1EmAtyE8nhslhZxdz4ehlawlU6uHf8g4B+PycGNO/7YFHtIzOIG+aa+9UB/9zdj+C4HkZcWDFx2a7GvTtLbyGNsGfcfQUSUvTfzjkbjlg=,iv:/v47OYruQPxx6xRXvMHLndmLMqj7RqdaWQmuvzML/Z8=,tag:nSe7qlq1p5NMSO70hfwczg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZTFVSXU3OEJKUmc5cXBr
            cXVZM1laZ2R1QmYvb2EzRlZJb3RIdDVRZlVnCjlWeEpPU09VcGJQN2cra2NUNnNN
            QnJDN3ZCSmpReDJrczk0VWx5dGtUUkkKLS0tIGljby9janBwS0hxRW5TWU1EZGV2
            Q012dzVmdSt5UndGczdpUUdNcHVUNFkKm7H+BSieO0s8x6Pkfey43zjw+r3MKRh0
            7uDv1Qnp3ZYIVb1bHbMPweEZNK3zTysH/lX5EQB3KoKTylWOu5m/Qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18ewkj2vf2uskukrusq5hnghrndeflalfes64dq3g273kyx29nprqvwz9n4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTnZjeFdZSlNSSEhoTHFx
            V25GZVh1eFVLSFUyai9qSHp3TWtINDRqRXhBCk4wc3dJMFhKTTZnNk1xaFcvQW1p
            Z2V3dE51TGZkSWFTTDJJSE5nbVVKckEKLS0tIGVYUXlNb3JSV0x4ZDhuTkpBTjV0
            a2FsS3dEQWhFSkk5Ui9aS3NaQm00OTgKjayNdy61AnHqQW1CcAzoqOoF5k1NVXE1
            X9VpjQ2oaTk+7z9Q6HZToCZ0esWifWso9lwJcG7H7XiwVh8qOjc4Ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174stazfxc7t4tszckfpvqlyteymr5vjzsukq3xrkf4n6mgsssfwsg2hhaf
    lastmodified: "2026-07-19T04:48:37Z"
    mac: ENC[AES256_GCM,data:oUkufv3NpTQAEv1aWfr55Qgk89m5DHyAcXPmMRpEScPiSkdoffu8QKsXMEe4DMpEey6oX4Mtz976IlARK2fC6JsPmk/UY9h3SluG3uXIuFBbVfbs0LMAHuQPdB+XDTxlUNAPpFabzPq1Aeby9xi8HL9WCphs9K8+55iLaU/5eGE=,iv:sAlXF5W+z2cYc9y+GLLV0V+xbV3lQ8NBLuqT2SQN9C8=,tag:4E/SAQgGbX25qdOh3a5NTQ==,type:str]
    pgp:
        - created_at: "2026-07-19T04:43:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvaQcs4TQKh4SAQdAOa/tAtfun5McAq2v5HXmrIMDdkRbbQcsNUmL2igzoDkw
            OuHJ1ya0pVM2NM+Nc9JwoERHTE/Ae9UuBL5hEEeHQp1JPHRnqy5Kht+myWcRdznX
            0l4B5pzRttRur74DfZAS7/dEYo40SbHp4mqd3/yCBfZqtMGUy3vm3A46k6I49HIN
            9dQNnm4zpGJYVNLYktQhmS9hmEWXAkz2FTeZCjzQ6UZx9jT7PViEBn4SH0rZPyeT
            =6pj7
            -----END PGP MESSAGE-----
          fp: BE06888200FCFE24713489557530F40B1361F796
    unencrypted_suffix: _unencrypted
    version: 3.13.1
