influxdb-token-env: ENC[AES256_GCM,data:vTs1VgXub3u+I0aS4d5uUSeItY9G8l1rBG1EmAtyE8nhslhZxdz4ehlawlU6uHf8g4B+PycGNO/7YFHtIzOIG+aa+9UB/9zdj+C4HkZcWDFx2a7GvTtLbyGNsGfcfQUSUvTfzjkbjlg=,iv:/v47OYruQPxx6xRXvMHLndmLMqj7RqdaWQmuvzML/Z8=,tag:nSe7qlq1p5NMSO70hfwczg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncnpubEMrak1Gaml0RFB6
            cFlUQ2tkMUlEaHpwd2liS2ZweWY0UDBsSTA0CnhjaFRDbkNmZUgvalhvZkJ0eHBP
            cDZyRWFDRm5lMXhSVmZ3Q3Axdmg1V3cKLS0tIGpxNlRTU3NadmV1UW1oUlhYZnk0
            MGxZMVhadnpBRDdvY2ZpQjZ2YWZVaFUKj/sKEhWej83daGP0D4dnOEXl36qlYj1V
            85ehutwF4lh0lgNZs61CTVRa87Y9QDACGeE4qTVfsxuEt4cz/gRMpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18ewkj2vf2uskukrusq5hnghrndeflalfes64dq3g273kyx29nprqvwz9n4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWVU1K0RLM0VLQ2J2U1Yx
            WmE0ZTg0VGgyTUorclBEYlJaY1VkNlFETW1vCld0RkRaUzJRRWpLSW8zTm51cHRw
            QUVZYStwOHZGS3BkdUhTdURmaW5ZUHcKLS0tIDFEMjh4TS9ZejByK2F6ZVBCaHRn
            bkp0bG9BYzduUDBmcXFnazFaRzZSc3cKLYWpw9vGCRC1HpQLkOY0D1/WLNBJtM36
            DxB/UoiKUPRac1MieEWnLEjqnTJzJ12L/Xq57YxtKQyWsT7wJxujCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174stazfxc7t4tszckfpvqlyteymr5vjzsukq3xrkf4n6mgsssfwsg2hhaf
    lastmodified: "2026-07-19T04:48:37Z"
    mac: ENC[AES256_GCM,data:oUkufv3NpTQAEv1aWfr55Qgk89m5DHyAcXPmMRpEScPiSkdoffu8QKsXMEe4DMpEey6oX4Mtz976IlARK2fC6JsPmk/UY9h3SluG3uXIuFBbVfbs0LMAHuQPdB+XDTxlUNAPpFabzPq1Aeby9xi8HL9WCphs9K8+55iLaU/5eGE=,iv:sAlXF5W+z2cYc9y+GLLV0V+xbV3lQ8NBLuqT2SQN9C8=,tag:4E/SAQgGbX25qdOh3a5NTQ==,type:str]
    pgp:
        - created_at: "2026-08-09T08:16:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DmZWgwGhfv/ISAQdAymyhVH1gdXNAPmKpsx2mdNl+MJUs/Bk0A3aakm/DS2ww
            GDEqMLudVzemG2XYjT1htskOHrHuJXLTVMNfy2aqQpvn2HgHCm8CKk65YVj3Cj3P
            0l4B8zo+EhyBh9doede8p68F5JspdadPGCfhgqyFFsIEyYbZVLekRYkph/amPQfX
            bsjG2Xtj10T43LzHMCEZFNRpw6PXkejc26jL/7nmjT2kABQ53qMU/+qPMM6VHgbV
            =M7k2
            -----END PGP MESSAGE-----
          fp: C1B386FF6BF5247A
        - created_at: "2026-08-09T08:16:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1gyu/tYOq5IARAAyx6en4UwNSSf4vFBOCFhnBxA3UfJx3ZArr/LG9Kqn79K
            By2k2nViWnrZ1Dw5TcnvV3TU9nXyyCE6KQ269chDsma5pDGGhldG8rAYSFPqGWYP
            qhT5fp5cH+e9aoMvHv9qJBTbpbEQjYnzuzVckJkxyzhcixOsqRLIddp5ALgO+BqZ
            xJuumefxHv8oGn9USQDqGNqou1UAEPiSXGb81wKlxi7j2A4Wh+C+1ylGfjqXJ8ih
            IujyiKLL70KKHcRyFEBx53FNuSCHFUitImZWMLaMfFr/5deMTOuC3WLICvyrcjN7
            10JJa2LFXHIKCJ/h+uj+rsAsYyMpODX9Dp9Ygt+S3FRDHnVUEz5FJbNLOPMWCWEV
            drFhpukDdnTjW0Z6yQmMNaMsgrjK17N9S7JFW+eScobWpBjYnv5acfGJwxkn+8es
            q+59YxF1a7EBOw9JDiXYNq8m3egl3imwM1CTxYtTc7Z6aXPuWZNwJvqXwBbAKPUA
            HiXM/DSBP2pDgnklKMHqTqWSjibBIND0bbRkB/t80/KQa1OqybsVfufpdVGdvDHP
            jVctUN2IHh1xf9qJkxn4/u89K5xqwUcAdThgQ2lr+DBkKxKbsTQA8I7KxNaiTZO5
            AJt8+vPEug8QI+53cGUHJIv++IMfBt4jjuEmaig6wvHCr21CXfVwxgIAdAau9ajS
            XgHmhYFovwwRxS/sfOjzsPuecbhhU4IyfOtJhNWM9OXQJV1Jgu6fIJWhmdzA6tsw
            DNqb7+z+iuuMQpjcZX5h/MGa/l2C/UoH8h4Wb8Ml3TY/zFRNW6ntIxQWNWn0Jt4=
            =xEWo
            -----END PGP MESSAGE-----
          fp: 50E40BBB4AF330FE
    unencrypted_suffix: _unencrypted
    version: 3.13.1
