grafana-secret-key: ENC[AES256_GCM,data:yoZa8asPtWteCZtVv5sQS0i0wxTapBGnvHqv9PRYVVogyDYwnp5Fr0H4IjUaKnSx/Nnz6ac/JJdNxYU2uWhvyg==,iv:n2tX1yv+VeMz0mF2M6fxJDRi7G3SG0c36a1SbtfJagc=,tag:SXk036O7BC5L+ZNJz+n65w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M2sxeTYrVkRvZThEMFQw
            eDl6Q0x6a2hsZS9tZnpzaWlnazFLSkRoZnlVCk1vWUZ5TUVBWEJyNmUweWQxWVlZ
            d3ArQVYyWUs1WEQvMDZjL3hqckVOUUEKLS0tIEpFZGZXR3B3QjRSWm5sekhmQStr
            UkwzMTlhVVR0bnU2Yk9HYlJhenFwbE0KKjFxo3rdO1L+/NnNiyBC7SIdLXl1YOyL
            g/QT6mOTQNgcuFGMSva/HFMmHPqIunOVzhPq+Nsd2OYHq2ck+jA/ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18ewkj2vf2uskukrusq5hnghrndeflalfes64dq3g273kyx29nprqvwz9n4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd0E0WktLLzVxbWdmYmxP
            OTZLcmVRcm04dlh6S2wwQkUzSStxQ1k1NFc4CmJyN2JTQjNDTjNRRjRVMU5DZEFj
            djZ4SUhzeUIzRXpTVG1JYlREb1I1dlUKLS0tIFBTMnBSZ3VIR2R1ZVRvMnRxMjNX
            RHFQRnliUEJxTU5mUjR2eWg5WStNdEkKrwO8JRnBT+svs4i5kHtbb+nnWvIwhRHB
            P5HoWV7ygzJhTsGlb6/YjguzX5d7JeN1p2UfkhM3llrh/ZIJbfL0nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174stazfxc7t4tszckfpvqlyteymr5vjzsukq3xrkf4n6mgsssfwsg2hhaf
    lastmodified: "2026-07-19T03:43:46Z"
    mac: ENC[AES256_GCM,data:1rYbA936/aZRTnFGBNC9ILDW6gUm6im6lQendmqPQCOoWRuZUC7C/gi215/XOEwkwy/VqzVEFuCGm/3LlDPh4/wDpsPbYf8mzt3qZfIWcqhyYSSsiKcD1n2nxNbMggRqsv5lKRU3ZjAGfES+dgSBZFx0vk5s97HmjZB1xwZ75uw=,iv:gz5tH+H62v3kqQXc8lG+s/BNLm/29ACLkWApkzwMsOQ=,tag:j+RyFp1tPA9EnZUQJ47nYg==,type:str]
    pgp:
        - created_at: "2026-08-09T08:16:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DmZWgwGhfv/ISAQdAiR0/LNlbmHZ0NZOY5TPMTO2sU+5tA/zXsPJbhfAPoXcw
            1PsHVIS9xE0PlYXoQ7r5bsfwiaqtlb4Sl5pBoN8YEvUs0O9xbhloPeZDmhIs9xR5
            0lwBDtogTTlZ0+IqpG3QB208CuVHNMEmCoOu9ufJ5x0kz+FbCPckpyRcUc436oW9
            InOydHChkQhLAV9GA3dtOcEeQ5o6klddQet+D03pyaVOsmcUirQdts+pbyIAAg==
            =1wcJ
            -----END PGP MESSAGE-----
          fp: C1B386FF6BF5247A
        - created_at: "2026-08-09T08:16:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1gyu/tYOq5IAQ//eh/TyM42edT+Zqez/IaVdwIr5DI0i5nfuZiaF75hydSI
            uk7+puZDfUWNYmPwoRT8bMrYlK2PGIMglFV/dz3W3w4yxYjxDZsKdStcRfDIeh88
            Mxe15aKSwmrJQtg6VBTY88WVuN+e8LmSbOJcL729qnvTuaXTKkyH9r1pf9TAe+jY
            ChkTZQ1L8pdDfSO/C3J53Lx2RMkyhNdKZ+VHmKKI3VbJQw9N403KSSnFA3TaPq8S
            AEpsmPtgfpOU81Xl8fspWuiwYcGoy6REewpKnwUKE7lgrLOZHxfEWqzx4b0/jiV4
            afiVJ/gCdI7hr77XIC0FDMY2QfPBEqheAfP7WFm4PvER0+gl3vrrfpYYako7g+h6
            HdNbl2WRupCbMMU9oUbPeOI2UZkO3H+j6BSk9Dv3uhwWClU97ILu/MX+hlNw19nK
            K7tVrmqXOhlfJ+Ew1iK+aVH9iyrOavAvOkRSKG+aPo9OMtvmm0kIm8flr1H3zRGa
            v7Z79NpqWNKQZQbM2smh8sVBbx8Lo1PV5cUB36/aQJbi543bp1KYbIoI/pxD8SQP
            gRJKv6Gy1P54bKxAN35wOvR1inuEEk8V1LhCtZoFXzPbS2YtaPyrQSmtIrvxM7CU
            dsu2F1RJ/aPUAdJbS8iSxd9nBsn05uKdJYzmBpG07fs2lfR8yBjVdBKMznm7GnLS
            XAG8QCgpXhjlpE24wwwKB/WFSoveNAKr6i8t+Ma00AV+W7ZNWEmA0D20La/I2BT8
            ReXnNrpNSI2QbeXRcIY0vqXBFFO7QH+TYfHiGfro2ZuurAYCZMGzVBalorI/
            =65r6
            -----END PGP MESSAGE-----
          fp: 50E40BBB4AF330FE
    unencrypted_suffix: _unencrypted
    version: 3.13.1
