grafana-secret-key: ENC[AES256_GCM,data:yoZa8asPtWteCZtVv5sQS0i0wxTapBGnvHqv9PRYVVogyDYwnp5Fr0H4IjUaKnSx/Nnz6ac/JJdNxYU2uWhvyg==,iv:n2tX1yv+VeMz0mF2M6fxJDRi7G3SG0c36a1SbtfJagc=,tag:SXk036O7BC5L+ZNJz+n65w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbXRqZkZ5QUZwdnROZWtw
            MStkelBMTnF0MXBHZTNTUjdzckoxcXVsQWp3CjdMU0Z1cE9SYTJ3SkU3NzNiSnl1
            RnFOaW4vOWFNbE8rS2FrU1R0S2MvQUUKLS0tIEpnMVBsVTVXMEtVb2xaeEVpYTk1
            Mi9QV3JzdjJZUW9PT2N0eGJCTTB1dzAKbbbxrMhbrACADCYg0G0h3p0sxJ4Ep1kC
            EOdSLiCRdWcfFAv7QWWKVtwIWrGLE1Q83r7Eu3DSVWCPYGczxaOUrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18ewkj2vf2uskukrusq5hnghrndeflalfes64dq3g273kyx29nprqvwz9n4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UHB1eXl6TmU5VXpmQUZ0
            YVBZMGd2Uks1Sjh1Q1VnNXllN0hEdlhxS2xnCnVqRkh0MUtqcUlHa05sck9QY2E3
            NFJ6aU5UM2xOcnJxVXByaW9MTUp5NHMKLS0tIDI1REYxd2VSWVcwSWZYdXFndGNE
            VFcycHZWZDhjejQrZzBTYkpoU3V5cjAKX1nWmL1sGJ3xbO7RIWNZZQFCWd3n8SUD
            RuVowtBpTCftWe2ONf0MUCL5qrq4YaP9HCmyXi5b2ArryrPFsZKavQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174stazfxc7t4tszckfpvqlyteymr5vjzsukq3xrkf4n6mgsssfwsg2hhaf
    lastmodified: "2026-07-19T03:43:46Z"
    mac: ENC[AES256_GCM,data:1rYbA936/aZRTnFGBNC9ILDW6gUm6im6lQendmqPQCOoWRuZUC7C/gi215/XOEwkwy/VqzVEFuCGm/3LlDPh4/wDpsPbYf8mzt3qZfIWcqhyYSSsiKcD1n2nxNbMggRqsv5lKRU3ZjAGfES+dgSBZFx0vk5s97HmjZB1xwZ75uw=,iv:gz5tH+H62v3kqQXc8lG+s/BNLm/29ACLkWApkzwMsOQ=,tag:j+RyFp1tPA9EnZUQJ47nYg==,type:str]
    pgp:
        - created_at: "2026-07-19T04:05:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvaQcs4TQKh4SAQdATtb4AEKQVRGy7+gWE0GgeiOqMsUnnvFqTklTZUL5tzsw
            RA+g7Yjo7dE1Jdc9ktLeaewMyBcrp6afHLJFi0LSgr0gQjw07QLkdEL5+gK/b2xU
            0lwB3BXq5pWasDOUepVYS2A0k82B/3bd6X/QVruzE1BJmaUfH4rPCChB0JTjFOaT
            Dl5hxf4x4vQZ82NCTe2sVBhpwj6ApMpFMLL1EGxOnx2LFsFNRjAFZgydiaj42Q==
            =GTGJ
            -----END PGP MESSAGE-----
          fp: BE06888200FCFE24713489557530F40B1361F796
    unencrypted_suffix: _unencrypted
    version: 3.13.1
