grafana-secret-key: ENC[AES256_GCM,data:yoZa8asPtWteCZtVv5sQS0i0wxTapBGnvHqv9PRYVVogyDYwnp5Fr0H4IjUaKnSx/Nnz6ac/JJdNxYU2uWhvyg==,iv:n2tX1yv+VeMz0mF2M6fxJDRi7G3SG0c36a1SbtfJagc=,tag:SXk036O7BC5L+ZNJz+n65w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TVIzVTY0Q1VRNkJ1bEJo
            a1B0YUU0eXVzNFJaVllUOTJERjc3MTRuK1hvCnF5N3hLL1kyMWtsL2NmdjhDc3I4
            TTZaemFzSUFoTDZtZHVVYzhGUjAvbkEKLS0tIFZ1WEJGTEV6RElQaGxJZEhtYi95
            eDEvY3dGSktCMEJQdXV0NlFyVHZ1emsKjuQ5HBHB2UyDWYCyTpMuBVTmwSGhrXXN
            gIZCOclEVlSkR1MZ79dQHm0cvPjn1+9LrLCLYRXjPDBqa8y/hFHpAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18ewkj2vf2uskukrusq5hnghrndeflalfes64dq3g273kyx29nprqvwz9n4
    lastmodified: "2026-07-19T03:43:46Z"
    mac: ENC[AES256_GCM,data:1rYbA936/aZRTnFGBNC9ILDW6gUm6im6lQendmqPQCOoWRuZUC7C/gi215/XOEwkwy/VqzVEFuCGm/3LlDPh4/wDpsPbYf8mzt3qZfIWcqhyYSSsiKcD1n2nxNbMggRqsv5lKRU3ZjAGfES+dgSBZFx0vk5s97HmjZB1xwZ75uw=,iv:gz5tH+H62v3kqQXc8lG+s/BNLm/29ACLkWApkzwMsOQ=,tag:j+RyFp1tPA9EnZUQJ47nYg==,type:str]
    pgp:
        - created_at: "2026-07-19T03:43:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvaQcs4TQKh4SAQdAkG/acTwQJ5cWmbdUl5HwMLtu0/zMVTYjyujkKrVgKWIw
            G2IeGnE2nzS2CCQAaWK++U0ezGVaGyttk8VRv+eV99o3ADDXSioEj5AmkdKGn53H
            0lwBKoRXlhC8hzQOAx80PPZ1tUEQByJ9DeFAXdnKK5XWTypvVBZEhMf37xM91m+5
            2FyqICmeAGIV9xM+A/puiShC9iSbFerawdkG5KCOpEEARgEpn/mEgneSRCtwgQ==
            =SkSE
            -----END PGP MESSAGE-----
          fp: BE06888200FCFE24713489557530F40B1361F796
    unencrypted_suffix: _unencrypted
    version: 3.13.1
